### ISSUE TITLE
Installing from Marketplace fails with "The following solutions are not available: GNU MCU Eclipse 4.1.1"

### ISSUE THREAD

**Issue by amq** [gnu-mcu-eclipse/org.eclipse.epp.packages#1]
Tested on two systems:

Windows 10
Eclipse Neon.3 (updating the plugins)
Java 8r131

Ubuntu 16.04
Eclipse Neon.3 (installing the plugins from scratch)
OpenJDK 8r131

**Comment by ilg-ul** [comment]
can you better document the steps you did so the problem can be reproduced?

**Comment by amq** [comment]
1. Install Ubuntu 16.04 from scratch
2. Install Eclipse Neon.3
3. Try installing the GNU MCU plugins from the Marketplace
4. Get an error:

```
The following solutions are not available: GNU MCU Eclipse 4.1.1 (id=ilg.gnumcueclipse.debug.gdbjtag.jlink.feature.group, ilg.gnumcueclipse.debug.gdbjtag.qemu.feature.group, ilg.gnumcueclipse.packs.feature.group, ilg.gnumcueclipse.managedbuild.cross.arm.feature.group, ilg.gnumcueclipse.managedbuild.cross.riscv.feature.group, ilg.gnumcueclipse.debug.gdbjtag.openocd.feature.group, ilg.gnumcueclipse.templates.stm.feature.group, site=http://gnu-mcu-eclipse.netlify.com/v4-neon-updates)
```

5. Try opening https://dl.bintray.com/gnu-mcu-eclipse/v4-neon-updates/ in browser to verify it's not some IP blacklisting etc, opens fine

**Comment by ilg-ul** [comment]
this tracker is attached to the project used to build and distribute the binary release of Neon.3 plus the plug-ins. in what way does the reported problem relate to them?

**Comment by amq** [comment]
Sorry, created it in [eclipse-plugins](https://github.com/gnu-mcu-eclipse/eclipse-plugins/issues/228)
