### ISSUE TITLE
Global Tool Paths setting missing

### ISSUE THREAD

**Issue by steronydh** [gnu-mcu-eclipse/org.eclipse.epp.packages#2]
I have all of the tools installed and working in an older version of Eclipse but the Global Tool Paths setting is missing in this install:

![image](https://user-images.githubusercontent.com/4245329/29263934-f483ec0e-80d2-11e7-8048-65b9f4bdc128.png)

**Comment by ilg-ul** [comment]
see the MCU separate page

**Comment by steronydh** [comment]
Found it, thanks.
